"""Update income table

Revision ID: 4b5031bab368
Revises: da8bbc55dffa
Create Date: 2025-02-06 14:02:13.040205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b5031bab368'
down_revision: Union[str, None] = 'da8bbc55dffa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('income_user_id_fkey', 'income', type_='foreignkey')
    op.create_foreign_key(None, 'income', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'income', type_='foreignkey')
    op.create_foreign_key('income_user_id_fkey', 'income', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
