"""Create a income table

Revision ID: 59c5014d91ba
Revises: 872065d49564
Create Date: 2025-02-06 11:20:28.559891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59c5014d91ba'
down_revision: Union[str, None] = '872065d49564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('income',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('income', sa.Float(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('income_added_at', sa.DATE(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('income')
    # ### end Alembic commands ###
