"""Added expenses table

Revision ID: b512635ea63d
Revises: 4b5031bab368
Create Date: 2025-02-07 10:31:08.778870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b512635ea63d'
down_revision: Union[str, None] = '4b5031bab368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('added_at', sa.DATE(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('income', sa.Column('added_at', sa.DATE(), server_default=sa.text('NOW()'), nullable=False))
    op.drop_column('income', 'income_added_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('income', sa.Column('income_added_at', sa.DATE(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('income', 'added_at')
    op.drop_table('expenses')
    # ### end Alembic commands ###
