"""Modified expenses table

Revision ID: d17f2663f5a3
Revises: b512635ea63d
Create Date: 2025-02-07 11:11:04.928781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd17f2663f5a3'
down_revision: Union[str, None] = 'b512635ea63d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expenses', 'category',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('groceries', 'utilities', 'housing', 'transportation', 'entertainment', 'hobby', 'medical', 'vacation', 'other', name='expenses_category'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expenses', 'category',
               existing_type=sa.Enum('groceries', 'utilities', 'housing', 'transportation', 'entertainment', 'hobby', 'medical', 'vacation', 'other', name='expenses_category'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
